//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.Razor {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeAnalysisResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeAnalysisResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.CodeAnalysis.Razor.CodeAnalysisResources", typeof(CodeAnalysisResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TagHelper_CouldNotFindMatchingEndBrace {
            get {
                return ResourceManager.GetString("TagHelper_CouldNotFindMatchingEndBrace", resourceCulture);
            }
        }
        
        internal static string TagHelper_InvalidAttributePrefixNotNull {
            get {
                return ResourceManager.GetString("TagHelper_InvalidAttributePrefixNotNull", resourceCulture);
            }
        }
        
        internal static string TagHelper_InvalidAttributeNameNotNullOrEmpty {
            get {
                return ResourceManager.GetString("TagHelper_InvalidAttributeNameNotNullOrEmpty", resourceCulture);
            }
        }
        
        internal static string TagHelper_InvalidAttributePrefixNull {
            get {
                return ResourceManager.GetString("TagHelper_InvalidAttributePrefixNull", resourceCulture);
            }
        }
        
        internal static string TagHelper_InvalidRequiredAttributeCharacter {
            get {
                return ResourceManager.GetString("TagHelper_InvalidRequiredAttributeCharacter", resourceCulture);
            }
        }
        
        internal static string TagHelper_InvalidRequiredAttributeMismatchedQuotes {
            get {
                return ResourceManager.GetString("TagHelper_InvalidRequiredAttributeMismatchedQuotes", resourceCulture);
            }
        }
        
        internal static string TagHelper_InvalidRequiredAttributeOperator {
            get {
                return ResourceManager.GetString("TagHelper_InvalidRequiredAttributeOperator", resourceCulture);
            }
        }
        
        internal static string TagHelper_PartialRequiredAttributeOperator {
            get {
                return ResourceManager.GetString("TagHelper_PartialRequiredAttributeOperator", resourceCulture);
            }
        }
        
        internal static string MarkupTransition_Description {
            get {
                return ResourceManager.GetString("MarkupTransition_Description", resourceCulture);
            }
        }
    }
}
